language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t gifen/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true gifen/docker-react npm run test -- --coverage